ru:
  start: Тесты по неврологии НМИЦ им. В.А. Алмазова
  about: "Этот бот предназначен для прохождения тестов по неврологии в НМИЦ им. В. А. Алмазова\nНажав /start, вы всегда можете начать заново\nС вопросами и предложениями обращайтесь [к автору](tg://user?id=378574596)"
  how_many_questions: Сколько вопросов Вам задать?
  ask_questions: 'Ответьте на %{questions} %{from_available}'
  right_answer: 'Правильный ответ: %{right_answer}'
  right: Верно
  more_than_one_answer: "Вы ответили более 1 раза подряд на 1 вопрос.\nЭто вызвало ошибку, пожалуйста, начните заново"
  finished: "Вы ответили верно на %{questions} из %{count}\nЧтобы начать заново, нажмите /start"
  question:
    zero: '%{count} вопросов'
    one: '%{count} вопрос'
    few: '%{count} вопроса'
    many: '%{count} вопросов'
    other: '%{count} вопроса'
  from_available:
    one: 'из %{count} имеющегося'
    few: 'из %{count} имеющихся'
    many: 'из %{count} имеющихся'
    other: 'из %{count} имеющихся'
