ru:
  start_message: Тесты по неврологии НМИЦ им. В.А. Алмазова
  about_message: "Этот бот предназначен для прохождения тестов по неврологии в НМИЦ им. В. А. Алмазова\nНажав /start, вы всегда можете начать заново\nС вопросами и предложениями обращайтесь [к автору](tg://user?id=378574596)"
  question:
    one: '%{count} вопрос'
    few: '%{count} вопроса'
    many: '%{count} вопросов'
    other: '%{count} вопросов'
